- name: bootstrap signoz
  hosts: localhost
  gather_facts: false  
  tasks:
    - name: docker compose up
      community.docker.docker_compose_v2:
        project_src: .
        files:
        - docker-compose.yml
        state: present
        docker_cli: /usr/bin/docker
        docker_host: unix:///var/run/docker.sock
    - import_tasks: lcbo/up.yml
      vars:
        db_user: lcbo
        db_name: lcbo
        db_password: Secret5555
        connect_user: 'devtedsuser'
        connect_password: 'devtedspass'
        connect_host: 'localhost'
